In [5]:
print("Hello, VS Code")

Hello, VS Code

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../Data for working/202506-divvy-tripdata.csv")

In [8]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member

In [9]:
df.shape

(678904, 13)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 678904 entries, 0 to 678903
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             678904 non-null  object
 1   rideable_type       678904 non-null  object
 2   started_at          678904 non-null  object
 3   ended_at            678904 non-null  object
 4   start_station_name  528000 non-null  object
 5   start_station_id    528000 non-null  object
 6   end_station_name    522132 non-null  object
 7   end_station_id      522132 non-null  object
 8   start_lat           678904 non-null  float64
 9   start_lng           678904 non-null  float64
 10  end_lat             677916 non-null  float64
 11  end_lng             677916 non-null  float64
 12  member_casual       678904 non-null  object
dtypes: float64(4), object(9)
memory usage: 67.3+ MB

In [11]:
df.isnull().sum()

ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    150904
start_station_id      150904
end_station_name      156772
end_station_id        156772
start_lat                  0
start_lng                  0
end_lat                  988
end_lng                  988
member_casual              0
dtype: int64

In [12]:
df = df.dropna(subset=['end_lat', 'end_lng'])

In [13]:
df.isnull().sum()

ride_id                    0
rideable_type              0
started_at                 0
ended_at                   0
start_station_name    150904
start_station_id      150904
end_station_name      155784
end_station_id        155784
start_lat                  0
start_lng                  0
end_lat                    0
end_lng                    0
member_casual              0
dtype: int64

In [14]:
df['started_at'] = pd.to_datetime(df['started_at'])
df['ended_at'] = pd.to_datetime(df['ended_at'])

df['ride_duration'] = (df['ended_at'] - df['started_at']).dt.total_seconds() / 60

In [15]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_duration
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member,13.805700
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,9.755217
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,9.518333
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member,12.091283
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member,10.174667

In [16]:
df['ride_duration'].describe()

count    677916.000000
mean         16.265276
std          32.151291
min           0.001183
25%           6.077117
50%          10.650692
75%          18.445100
max        1499.931883
Name: ride_duration, dtype: float64

In [17]:
df = df[df['ride_duration'] > 0]
df = df[df['ride_duration'] <= 180]

In [18]:
df['ride_duration'].describe()

count    676430.000000
mean         15.248368
std          16.360730
min           0.001183
25%           6.068104
50%          10.627367
75%          18.364908
max         179.986417
Name: ride_duration, dtype: float64

In [19]:
missing = df.isnull().sum()

missing_percent = (missing / len(df)) * 100

missing_df = pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percent
})

missing_df.sort_values(by="Percentage", ascending=False)

                    Missing Values  Percentage
end_station_name            155658   23.011694
end_station_id              155658   23.011694
start_station_name          150824   22.297060
start_station_id            150824   22.297060
ride_id                          0    0.000000
rideable_type                    0    0.000000
started_at                       0    0.000000
ended_at                         0    0.000000
start_lat                        0    0.000000
start_lng                        0    0.000000
end_lat                          0    0.000000
end_lng                          0    0.000000
member_casual                    0    0.000000
ride_duration                    0    0.000000

In [20]:
df.describe(include="all")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_duration
count,676430,676430,676430,676430,525606,525606,520772,520772,676430.000000,676430.000000,676430.000000,676430.000000,676430,676430.000000
unique,676430,2,NaN,NaN,1376,1376,1364,1363,NaN,NaN,NaN,NaN,2,NaN
top,0E43949BF937C7DA,electric_bike,NaN,NaN,Streeter Dr & Grand Ave,CHI01747,Streeter Dr & Grand Ave,CHI01747,NaN,NaN,NaN,NaN,member,NaN
freq,1,424575,NaN,NaN,9988,9988,9964,9964,NaN,NaN,NaN,NaN,386435,NaN
mean,NaN,NaN,2025-06-16 19:33:52.414725632,2025-06-16 19:49:07.316788224,NaN,NaN,NaN,NaN,41.906565,-87.646247,41.907102,-87.646597,NaN,15.248368
min,NaN,NaN,2025-05-31 22:21:17.577000,2025-06-01 00:00:04.185000,NaN,NaN,NaN,NaN,41.648501,-87.890000,41.490000,-88.060000,NaN,0.001183
25%,NaN,NaN,2025-06-09 17:17:34.352749824,2025-06-09 17:32:19.106249984,NaN,NaN,NaN,NaN,41.883589,-87.660000,41.883984,-87.660000,NaN,6.068104
50%,NaN,NaN,2025-06-16 19:58:04.680000,2025-06-16 20:13:30.596000,NaN,NaN,NaN,NaN,41.900000,-87.641170,41.900960,-87.641190,NaN,10.627367
75%,NaN,NaN,2025-06-24 08:39:08.388749824,2025-06-24 08:50:29.632499968,NaN,NaN,NaN,NaN,41.931320,-87.629791,41.932418,-87.629912,NaN,18.364908
max,NaN,NaN,2025-06-30 23:57:15.111000,2025-06-30 23:59:49.808000,NaN,NaN,NaN,NaN,42.070000,-87.528232,42.170000,-87.420000,NaN,179.986417
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.041999,0.026966,0.042262,0.027187,NaN,16.360730

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
(df["ride_duration"] < 1).sum()

np.int64(19622)

In [23]:
df.nsmallest(10, "ride_duration")[["ride_id", "started_at", "ended_at", "ride_duration", "member_casual"]]

,ride_id,started_at,ended_at,ride_duration,member_casual
645818,82D62BB042C28F8D,2025-06-01 04:27:50.958,2025-06-01 04:27:51.029,0.001183,casual
312807,7532E07AE2BBF0D0,2025-06-03 17:51:35.861,2025-06-03 17:51:36.038,0.002950,casual
281653,A43504FBBB6288BB,2025-06-05 17:53:18.914,2025-06-05 17:53:19.093,0.002983,member
335526,77D313181A9F481B,2025-06-12 17:09:14.961,2025-06-12 17:09:15.154,0.003217,member
320974,4F71B728EC97B373,2025-06-12 09:26:24.829,2025-06-12 09:26:25.032,0.003383,member
310927,2D3ECCC4C6F5A8BC,2025-06-11 15:47:57.813,2025-06-11 15:47:58.017,0.003400,casual
316382,C01410963784BDCC,2025-06-19 13:35:33.885,2025-06-19 13:35:34.097,0.003533,member
678846,687F8E84D8A84DC4,2025-06-21 18:53:30.949,2025-06-21 18:53:31.168,0.003650,casual
657934,E9E3777AF51E8592,2025-06-09 20:49:50.779,2025-06-09 20:49:51.005,0.003767,member
321761,F61BF457469AC674,2025-06-29 14:16:40.893,2025-06-29 14:16:41.122,0.003817,member

In [24]:
import os

folder_path = "../Data for working"

csv_files = sorted([file for file in os.listdir(folder_path) if file.endswith(".csv")])

csv_files

['202506-divvy-tripdata.csv',
 '202507-divvy-tripdata.csv',
 '202508-divvy-tripdata.csv',
 '202509-divvy-tripdata.csv',
 '202510-divvy-tripdata.csv',
 '202511-divvy-tripdata.csv',
 '202512-divvy-tripdata.csv',
 '202601-divvy-tripdata.csv',
 '202602-divvy-tripdata.csv',
 '202603-divvy-tripdata.csv',
 '202604-divvy-tripdata.csv',
 '202605-divvy-tripdata.csv']

In [25]:
len(csv_files)

12

In [26]:
df_list = []

for file in csv_files:
    temp_df = pd.read_csv(os.path.join(folder_path, file))
    temp_df["source_file"] = file
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index=True)

In [27]:
df.shape

(5848703, 14)

In [28]:
df[df["ride_duration"] == df["ride_duration"].max()]

KeyError: 'ride_duration'

In [ ]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,source_file
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member,202506-divvy-tripdata.csv
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,202506-divvy-tripdata.csv
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,202506-divvy-tripdata.csv
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member,202506-divvy-tripdata.csv
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member,202506-divvy-tripdata.csv

In [ ]:
df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'source_file'],
      dtype='object')

In [ ]:
df["started_at"] = pd.to_datetime(df["started_at"])
df["ended_at"] = pd.to_datetime(df["ended_at"])

ValueError: time data "15:08.5" doesn't match format "%Y-%m-%d %H:%M:%S.%f", at position 678904. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
import os
import pandas as pd

folder_path = "../Data for working"

for file in csv_files:
    temp_df = pd.read_csv(os.path.join(folder_path, file))

    try:
        pd.to_datetime(temp_df["started_at"])
        pd.to_datetime(temp_df["ended_at"])
        print(f"✅ {file} - OK")

    except Exception as e:
        print(f"❌ {file}")
        print(e)
        print("-" * 60)

✅ 202506-divvy-tripdata.csv - OK

C:\Users\UC\AppData\Local\Temp\ipykernel_9784\3037122242.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(temp_df["started_at"])

❌ 202507-divvy-tripdata.csv
hour must be in 0..23: 57:38.9, at position 1
------------------------------------------------------------
✅ 202508-divvy-tripdata.csv - OK
✅ 202509-divvy-tripdata.csv - OK
✅ 202510-divvy-tripdata.csv - OK
✅ 202511-divvy-tripdata.csv - OK
✅ 202512-divvy-tripdata.csv - OK
✅ 202601-divvy-tripdata.csv - OK
✅ 202602-divvy-tripdata.csv - OK
✅ 202603-divvy-tripdata.csv - OK
✅ 202604-divvy-tripdata.csv - OK
✅ 202605-divvy-tripdata.csv - OK

In [ ]:
july_df = pd.read_csv("../Data for working/202507-divvy-tripdata.csv")

In [ ]:
july_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,455D43BD91D73437,classic_bike,15:08.5,25:47.1,Lincoln Ave & Diversey Pkwy,CHI00285,Lincoln Ave & Addison St,CHI00478,41.932225,-87.658617,41.946176,-87.673308,member
1,9D4A6B723ECD98CA,classic_bike,57:38.9,06:35.8,Cottage Grove Ave & Oakwood Blvd,CHI00400,Cottage Grove Ave & 47th St,CHI00488,41.822985,-87.607100,41.809855,-87.606755,member
2,C57044CF523302ED,classic_bike,49:28.1,15:29.0,Theater on the Lake,CHI00420,Winthrop Ave & Lawrence Ave,CHI00391,41.926277,-87.630834,41.968812,-87.657659,member
3,AFD35552E6685B6E,electric_bike,36:21.1,46:54.7,Pine Grove Ave & Waveland Ave,CHI00354,Winthrop Ave & Lawrence Ave,CHI00391,41.949473,-87.646453,41.968812,-87.657659,member
4,C0582EBAA6CED519,classic_bike,43:45.2,57:06.7,Theater on the Lake,CHI00420,Sheffield Ave & Wellington Ave,CHI00274,41.926277,-87.630834,41.936253,-87.652662,member

In [ ]:
july_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='object')

In [ ]:
july_df[["started_at", "ended_at"]].head(10)

  started_at ended_at
0    15:08.5  25:47.1
1    57:38.9  06:35.8
2    49:28.1  15:29.0
3    36:21.1  46:54.7
4    43:45.2  57:06.7
5    21:48.0  24:59.5
6    28:46.8  40:16.4
7    43:30.7  59:57.4
8    14:04.1  24:59.7
9    03:15.7  23:13.4

In [ ]:
july_df["started_at"].str.len().value_counts()

started_at
7    763432
Name: count, dtype: int64

In [ ]:
july_df = pd.read_csv("../Data for working/202507-divvy-tripdata.csv", dtype=str)

print(july_df["started_at"].head(10).tolist())

['15:08.5', '57:38.9', '49:28.1', '36:21.1', '43:45.2', '21:48.0', '28:46.8', '43:30.7', '14:04.1', '03:15.7']

In [ ]:
with open("../Data for working/202507-divvy-tripdata.csv", "r", encoding="utf-8") as f:
    for i in range(5):
        print(repr(f.readline()))

'ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual\n'
'455D43BD91D73437,classic_bike,15:08.5,25:47.1,Lincoln Ave & Diversey Pkwy,CHI00285,Lincoln Ave & Addison St,CHI00478,41.932225,-87.658617,41.946176,-87.673308,member\n'
'9D4A6B723ECD98CA,classic_bike,57:38.9,06:35.8,Cottage Grove Ave & Oakwood Blvd,CHI00400,Cottage Grove Ave & 47th St,CHI00488,41.822985,-87.6071,41.809855,-87.606755,member\n'
'C57044CF523302ED,classic_bike,49:28.1,15:29.0,Theater on the Lake,CHI00420,Winthrop Ave & Lawrence Ave,CHI00391,41.926277,-87.630834,41.968812,-87.657659,member\n'
'AFD35552E6685B6E,electric_bike,36:21.1,46:54.7,Pine Grove Ave & Waveland Ave,CHI00354,Winthrop Ave & Lawrence Ave,CHI00391,41.94947274,-87.64645278,41.968812,-87.657659,member\n'

In [ ]:
print(july_df.shape)

(763432, 13)

In [ ]:
print(july_df["ride_id"].nunique())

763432

In [ ]:
july_df = pd.read_csv("../Data for working/202507-divvy-tripdata.csv")

july_df[["started_at", "ended_at"]].head(10)

                started_at                 ended_at
0  2025-07-05 17:15:08.456  2025-07-05 17:25:47.079
1  2025-07-01 13:57:38.878  2025-07-01 14:06:35.780
2  2025-07-31 16:49:28.142  2025-07-31 17:15:28.999
3  2025-07-17 09:36:21.058  2025-07-17 09:46:54.706
4  2025-07-02 18:43:45.213  2025-07-02 18:57:06.687
5  2025-07-14 19:21:47.976  2025-07-14 19:24:59.535
6  2025-07-10 18:28:46.817  2025-07-10 18:40:16.371
7  2025-07-27 13:43:30.714  2025-07-27 13:59:57.433
8  2025-07-23 20:14:04.150  2025-07-23 20:24:59.733
9  2025-07-23 21:03:15.690  2025-07-23 21:23:13.370

In [ ]:
july_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 763432 entries, 0 to 763431
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ride_id             763432 non-null  object
 1   rideable_type       763432 non-null  object
 2   started_at          763432 non-null  object
 3   ended_at            763432 non-null  object
 4   start_station_name  589903 non-null  object
 5   start_station_id    589903 non-null  object
 6   end_station_name    581926 non-null  object
 7   end_station_id      581926 non-null  object
 8   start_lat           763432 non-null  float64
 9   start_lng           763432 non-null  float64
 10  end_lat             762461 non-null  float64
 11  end_lng             762461 non-null  float64
 12  member_casual       763432 non-null  object
dtypes: float64(4), object(9)
memory usage: 75.7+ MB

In [ ]:
print(july_df.iloc[0]["started_at"])

2025-07-05 17:15:08.456

In [ ]:
import pandas as pd
import os

folder_path = "../Data for working"

csv_files = sorted([
    file for file in os.listdir(folder_path)
    if file.endswith(".csv")
])

df_list = []

for file in csv_files:
    temp_df = pd.read_csv(os.path.join(folder_path, file))
    temp_df["source_file"] = file
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index=True)

In [ ]:
df.shape

(5848703, 14)

In [ ]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,source_file
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member,202506-divvy-tripdata.csv
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,202506-divvy-tripdata.csv
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,202506-divvy-tripdata.csv
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member,202506-divvy-tripdata.csv
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member,202506-divvy-tripdata.csv

In [ ]:
df["started_at"] = pd.to_datetime(df["started_at"])
df["ended_at"] = pd.to_datetime(df["ended_at"])

In [ ]:
df["ride_duration"] = (
    df["ended_at"] - df["started_at"]
).dt.total_seconds() / 60

In [ ]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,source_file,ride_duration
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member,202506-divvy-tripdata.csv,13.805700
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,202506-divvy-tripdata.csv,9.755217
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,202506-divvy-tripdata.csv,9.518333
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member,202506-divvy-tripdata.csv,12.091283
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member,202506-divvy-tripdata.csv,10.174667

In [ ]:
df["ride_duration"].describe()

count    5.848703e+06
mean     1.598668e+01
std      5.510297e+01
min     -5.479480e+01
25%      5.372292e+00
50%      9.402117e+00
75%      1.654735e+01
max      1.574900e+03
Name: ride_duration, dtype: float64

In [ ]:
(df["ride_duration"] < 0).sum()

np.int64(29)

In [ ]:
df.loc[df["ride_duration"] < 0,
       ["ride_id", "started_at", "ended_at", "ride_duration", "source_file"]].head(10)

,ride_id,started_at,ended_at,ride_duration,source_file
3618432,5D010AFEA6850513,2025-11-02 01:52:37.475,2025-11-02 01:13:24.728,-39.212450,202511-divvy-tripdata.csv
3619980,D1E5316AD88ECD45,2025-11-02 01:50:39.702,2025-11-02 01:14:04.164,-36.592300,202511-divvy-tripdata.csv
3621974,3AF2F8908C9386F8,2025-11-02 01:57:57.512,2025-11-02 01:33:52.225,-24.088117,202511-divvy-tripdata.csv
3636870,19386939ECD81B33,2025-11-02 01:55:34.399,2025-11-02 01:21:31.873,-34.042100,202511-divvy-tripdata.csv
3645238,083534D28DA37F72,2025-11-02 01:17:57.001,2025-11-02 01:05:27.752,-12.487483,202511-divvy-tripdata.csv
3689823,4A659F1BB40EDBF7,2025-11-02 01:55:38.177,2025-11-02 01:04:35.315,-51.047700,202511-divvy-tripdata.csv
3715376,DA5386E5759667EC,2025-11-02 01:51:31.704,2025-11-02 01:05:47.339,-45.739417,202511-divvy-tripdata.csv
3720834,985A3462DAACFFCF,2025-11-02 01:59:07.835,2025-11-02 01:05:19.214,-53.810350,202511-divvy-tripdata.csv
3740757,434E3D11ABA96891,2025-11-02 01:59:40.156,2025-11-02 01:08:51.303,-50.814217,202511-divvy-tripdata.csv
3750575,9288498F5630E3AD,2025-11-02 01:49:48.360,2025-11-02 01:02:40.976,-47.123067,202511-divvy-tripdata.csv

In [ ]:
# Remove rides with negative duration
df = df[df["ride_duration"] >= 0]

In [ ]:
(df["ride_duration"] < 0).sum()

np.int64(0)

In [ ]:
df.shape

(5848674, 15)

In [ ]:
# Display summary statistics for ride duration
df["ride_duration"].describe()

count    5.848674e+06
mean     1.598697e+01
std      5.510295e+01
min      7.666667e-04
25%      5.372350e+00
50%      9.402183e+00
75%      1.654738e+01
max      1.574900e+03
Name: ride_duration, dtype: float64

In [ ]:
# Count rides longer than 24 hours (1440 minutes)
(df["ride_duration"] > 1440).sum()

np.int64(5843)

In [ ]:
# Display rides longer than 24 hours
df.loc[
    df["ride_duration"] > 1440,
    ["ride_id",
     "started_at",
     "ended_at",
     "ride_duration",
     "member_casual",
     "rideable_type",
     "source_file"]
]

,ride_id,started_at,ended_at,ride_duration,member_casual,rideable_type,source_file
2845,F477BCD0F06A8F03,2025-06-14 19:59:13.665,2025-06-15 20:59:09.648,1499.933050,casual,classic_bike,202506-divvy-tripdata.csv
2942,86E6DD95D1D1CE8B,2025-06-07 12:21:33.412,2025-06-08 13:21:13.290,1499.664633,casual,classic_bike,202506-divvy-tripdata.csv
2978,986604F99138CF09,2025-06-12 22:20:26.283,2025-06-13 23:20:17.547,1499.854400,casual,classic_bike,202506-divvy-tripdata.csv
4414,AC9364BA560C323F,2025-06-28 19:25:28.222,2025-06-29 20:25:22.649,1499.907117,member,classic_bike,202506-divvy-tripdata.csv
6452,CDC926E3C87710F4,2025-06-14 19:46:18.795,2025-06-15 20:32:30.584,1486.196483,casual,classic_bike,202506-divvy-tripdata.csv
...,...,...,...,...,...,...,...
5814621,8DFE15E8A005B747,2026-05-23 02:19:39.330,2026-05-24 03:19:17.440,1499.635167,casual,classic_bike,202605-divvy-tripdata.csv
5814695,FEEF7DF08E5C4E1D,2026-05-11 18:40:06.641,2026-05-12 19:39:53.897,1499.787600,casual,classic_bike,202605-divvy-tripdata.csv
5814917,D5B65C34DDD23C72,2026-05-23 18:12:42.844,2026-05-24 19:12:20.178,1499.622233,casual,classic_bike,202605-divvy-tripdata.csv
5814942,36A3BB435C883376,2026-05-30 08:39:00.103,2026-05-31 09:38:47.848,1499.795750,member,classic_bike,202605-divvy-tripdata.csv
5815000,802D1345ACAF5EFB,2026-05-24 16:08:12.337,2026-05-25 17:07:51.932,1499.659917,casual,classic_bike,202605-divvy-tripdata.csv

In [ ]:
# Count member and casual users for rides longer than 24 hours
df[df["ride_duration"] > 1440]["member_casual"].value_counts()

member_casual
casual    4809
member    1034
Name: count, dtype: int64

In [ ]:
# Count bike types for rides longer than 24 hours
df[df["ride_duration"] > 1440]["rideable_type"].value_counts()

rideable_type
classic_bike    5843
Name: count, dtype: int64

In [ ]:
# Count long rides by source file (month)
df[df["ride_duration"] > 1440]["source_file"].value_counts().sort_index()

source_file
202506-divvy-tripdata.csv    983
202507-divvy-tripdata.csv    978
202508-divvy-tripdata.csv    702
202509-divvy-tripdata.csv    618
202510-divvy-tripdata.csv    599
202511-divvy-tripdata.csv    337
202512-divvy-tripdata.csv    125
202601-divvy-tripdata.csv    191
202602-divvy-tripdata.csv    117
202603-divvy-tripdata.csv    266
202604-divvy-tripdata.csv    354
202605-divvy-tripdata.csv    573
Name: count, dtype: int64

In [ ]:
# Display the 10 longest rides
df.nlargest(10, "ride_duration")[
    [
        "ride_id",
        "ride_duration",
        "started_at",
        "ended_at",
        "member_casual",
        "rideable_type",
        "source_file"
    ]
]

,ride_id,ride_duration,started_at,ended_at,member_casual,rideable_type,source_file
307513,F7CAE51D367E737B,1574.900183,2025-06-08 14:44:02.253,2025-06-09 16:58:56.264,casual,classic_bike,202506-divvy-tripdata.csv
4497253,C82393BDD3070D5D,1559.950183,2026-03-07 16:07:09.988,2026-03-08 18:07:06.999,casual,classic_bike,202603-divvy-tripdata.csv
4574414,250556580DD308BE,1559.903683,2026-03-07 23:51:38.812,2026-03-09 01:51:33.033,member,classic_bike,202603-divvy-tripdata.csv
4570940,266FF1F3D3203623,1559.893867,2026-03-07 12:29:39.955,2026-03-08 14:29:33.587,casual,classic_bike,202603-divvy-tripdata.csv
4575336,F2DADD2100A676E7,1559.882583,2026-03-07 09:43:11.203,2026-03-08 11:43:04.158,casual,classic_bike,202603-divvy-tripdata.csv
4497385,EB04F9C062AAAF6A,1559.865450,2026-03-07 09:33:18.048,2026-03-08 11:33:09.975,casual,classic_bike,202603-divvy-tripdata.csv
4569165,7CFD1B6B5319BB28,1559.853767,2026-03-07 12:20:32.025,2026-03-08 14:20:23.251,casual,classic_bike,202603-divvy-tripdata.csv
4569168,B35EFB4539BB4B2B,1559.777383,2026-03-07 02:41:16.669,2026-03-08 04:41:03.312,casual,classic_bike,202603-divvy-tripdata.csv
4613430,13769591C639EB0C,1559.676067,2026-03-07 12:45:52.881,2026-03-08 14:45:33.445,member,classic_bike,202603-divvy-tripdata.csv
4452669,A679963188E41606,1559.653867,2026-03-07 14:40:43.466,2026-03-08 16:40:22.698,casual,classic_bike,202603-divvy-tripdata.csv

In [ ]:
# Count rides longer than 25 hours (1500 minutes)
(df["ride_duration"] > 1500).sum()

np.int64(13)

In [ ]:
# Show rides longer than 25 hours
df[df["ride_duration"] > 1500][
    [
        "ride_duration",
        "started_at",
        "ended_at",
        "source_file"
    ]
].sort_values("ride_duration", ascending=False)

,ride_duration,started_at,ended_at,source_file
307513,1574.900183,2025-06-08 14:44:02.253,2025-06-09 16:58:56.264,202506-divvy-tripdata.csv
4497253,1559.950183,2026-03-07 16:07:09.988,2026-03-08 18:07:06.999,202603-divvy-tripdata.csv
4574414,1559.903683,2026-03-07 23:51:38.812,2026-03-09 01:51:33.033,202603-divvy-tripdata.csv
4570940,1559.893867,2026-03-07 12:29:39.955,2026-03-08 14:29:33.587,202603-divvy-tripdata.csv
4575336,1559.882583,2026-03-07 09:43:11.203,2026-03-08 11:43:04.158,202603-divvy-tripdata.csv
4497385,1559.865450,2026-03-07 09:33:18.048,2026-03-08 11:33:09.975,202603-divvy-tripdata.csv
4569165,1559.853767,2026-03-07 12:20:32.025,2026-03-08 14:20:23.251,202603-divvy-tripdata.csv
4569168,1559.777383,2026-03-07 02:41:16.669,2026-03-08 04:41:03.312,202603-divvy-tripdata.csv
4613430,1559.676067,2026-03-07 12:45:52.881,2026-03-08 14:45:33.445,202603-divvy-tripdata.csv
4452669,1559.653867,2026-03-07 14:40:43.466,2026-03-08 16:40:22.698,202603-divvy-tripdata.csv
4573734,1559.643850,2026-03-07 12:28:27.947,2026-03-08 14:28:06.578,202603-divvy-tripdata.csv
701454,1500.896883,2025-07-20 15:15:45.610,2025-07-21 16:16:39.423,202507-divvy-tripdata.csv
830476,1500.617917,2025-07-29 18:45:24.786,2025-07-30 19:46:01.861,202507-divvy-tripdata.csv

In [ ]:
# Check for rides shorter than 1 minute
(df["ride_duration"] < 1).sum()

np.int64(161323)

In [ ]:
# Display some rides shorter than 1 minute
df.loc[
    df["ride_duration"] < 1,
    ["ride_id", "ride_duration", "member_casual", "source_file"]
].head(20)

               ride_id  ride_duration member_casual                source_file
43    A31269F41F4B4218       0.998750        member  202506-divvy-tripdata.csv
67    869F3C8B0E939C41       0.083117        casual  202506-divvy-tripdata.csv
152   66908344719E9FB3       0.146633        casual  202506-divvy-tripdata.csv
207   1C4A9F95815ED0FE       0.479433        casual  202506-divvy-tripdata.csv
298   26D86A70C626000F       0.102950        member  202506-divvy-tripdata.csv
403   C13B67061879B25D       0.240533        casual  202506-divvy-tripdata.csv
404   AE6D06E4C9F455DD       0.328083        casual  202506-divvy-tripdata.csv
427   836BD70AD9A71642       0.054467        member  202506-divvy-tripdata.csv
829   2E8546B35E848FFD       0.614283        casual  202506-divvy-tripdata.csv
833   9A9D7065BEE1A6C0       0.953300        member  202506-divvy-tripdata.csv
854   87BCC2D4E498600F       0.348783        member  202506-divvy-tripdata.csv
856   D1A53962C2977DCD       0.049450        member  202506-divvy-tripdata.csv
906   D006DB36706BE2FF       0.045550        casual  202506-divvy-tripdata.csv
913   5A2D0878E4CD379B       0.424417        member  202506-divvy-tripdata.csv
996   6584CE90BB87A50E       0.021300        member  202506-divvy-tripdata.csv
1004  D127F9BCADBCE207       0.702750        casual  202506-divvy-tripdata.csv
1100  A37F0FDDF1430D74       0.051683        member  202506-divvy-tripdata.csv
1102  084908809D3BAC88       0.417083        casual  202506-divvy-tripdata.csv
1113  8A2C1F0002EE3F49       0.395800        casual  202506-divvy-tripdata.csv
1115  7F94906C7908EC68       0.192533        casual  202506-divvy-tripdata.csv

In [ ]:
# Check member vs casual for rides shorter than 1 minute

df[df["ride_duration"] < 1]["member_casual"].value_counts()

member_casual
casual    82105
member    79218
Name: count, dtype: int64

In [ ]:
# Check bike type for rides shorter than 1 minute

df[df["ride_duration"] < 1]["rideable_type"].value_counts()

rideable_type
electric_bike    161323
Name: count, dtype: int64

In [ ]:
# Check month distribution for rides shorter than 1 minute

df[df["ride_duration"] < 1]["source_file"].value_counts().sort_index()

source_file
202506-divvy-tripdata.csv    19622
202507-divvy-tripdata.csv    23630
202508-divvy-tripdata.csv    22938
202509-divvy-tripdata.csv    18293
202510-divvy-tripdata.csv    17016
202511-divvy-tripdata.csv     9520
202512-divvy-tripdata.csv     3961
202601-divvy-tripdata.csv     3846
202602-divvy-tripdata.csv     4022
202603-divvy-tripdata.csv     8286
202604-divvy-tripdata.csv    12420
202605-divvy-tripdata.csv    17769
Name: count, dtype: int64

In [ ]:
# Check member vs casual for rides shorter than 1 minute

df[df["ride_duration"] < 1]["member_casual"].value_counts()

member_casual
casual    82105
member    79218
Name: count, dtype: int64

In [ ]:
# Check bike type for rides shorter than 1 minute

df[df["ride_duration"] < 1]["rideable_type"].value_counts()

rideable_type
electric_bike    161323
Name: count, dtype: int64

In [ ]:
# Check month distribution for rides shorter than 1 minute

df[df["ride_duration"] < 1]["source_file"].value_counts().sort_index()

source_file
202506-divvy-tripdata.csv    19622
202507-divvy-tripdata.csv    23630
202508-divvy-tripdata.csv    22938
202509-divvy-tripdata.csv    18293
202510-divvy-tripdata.csv    17016
202511-divvy-tripdata.csv     9520
202512-divvy-tripdata.csv     3961
202601-divvy-tripdata.csv     3846
202602-divvy-tripdata.csv     4022
202603-divvy-tripdata.csv     8286
202604-divvy-tripdata.csv    12420
202605-divvy-tripdata.csv    17769
Name: count, dtype: int64

In [ ]:
df["month"] = df["started_at"].dt.month_name()

In [ ]:
df["day_of_week"] = df["started_at"].dt.day_name()

In [ ]:
df["hour"] = df["started_at"].dt.hour

In [ ]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,source_file,ride_duration,month,day_of_week,hour
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member,202506-divvy-tripdata.csv,13.805700,June,Thursday,21
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,202506-divvy-tripdata.csv,9.755217,June,Saturday,13
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,202506-divvy-tripdata.csv,9.518333,June,Monday,13
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member,202506-divvy-tripdata.csv,12.091283,June,Sunday,12
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member,202506-divvy-tripdata.csv,10.174667,June,Thursday,7

In [ ]:
# সব column-এর নাম দেখবো
df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'source_file', 'ride_duration', 'month', 'day_of_week',
       'hour'],
      dtype='object')

In [ ]:
# Display basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5848674 entries, 0 to 5848702
Data columns (total 18 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          datetime64[ns]
 3   ended_at            datetime64[ns]
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
 13  source_file         object
 14  ride_duration       float64
 15  month               object
 16  day_of_week         object
 17  hour                int32
dtypes: datetime64[ns](2), float64(5), int32(1), object(10)
memory usage: 825.5+ MB

In [ ]:
# Count the number of rides for each rider type
df["member_casual"].value_counts()

member_casual
member    3748418
casual    2100256
Name: count, dtype: int64

In [ ]:
# Extract month number (1-12)
df["month"] = df["started_at"].dt.month

# Extract month name (January, February...)
df["month_name"] = df["started_at"].dt.month_name()

# Extract day of month
df["day"] = df["started_at"].dt.day

# Extract day name (Monday, Tuesday...)
df["day_of_week"] = df["started_at"].dt.day_name()

# Extract hour (0-23)
df["hour"] = df["started_at"].dt.hour

# Extract year
df["year"] = df["started_at"].dt.year

In [ ]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,end_lng,member_casual,source_file,ride_duration,month,day_of_week,hour,month_name,day,year
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,...,-87.629912,member,202506-divvy-tripdata.csv,13.805700,6,Thursday,21,June,5,2025
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,...,-87.638506,member,202506-divvy-tripdata.csv,9.755217,6,Saturday,13,June,14,2025
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,...,-87.638506,member,202506-divvy-tripdata.csv,9.518333,6,Monday,13,June,9,2025
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,...,-87.650000,member,202506-divvy-tripdata.csv,12.091283,6,Sunday,12,June,15,2025
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,...,-87.690000,member,202506-divvy-tripdata.csv,10.174667,6,Thursday,7,June,19,2025

In [ ]:
df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'source_file', 'ride_duration', 'month', 'day_of_week',
       'hour', 'month_name', 'day', 'year'],
      dtype='object')

In [ ]:
# Count total rides by user type
df["member_casual"].value_counts()

member_casual
member    3748418
casual    2100256
Name: count, dtype: int64

In [ ]:
# Calculate percentage of each user type
round(df["member_casual"].value_counts(normalize=True) * 100, 2)

member_casual
member    64.09
casual    35.91
Name: proportion, dtype: float64

In [ ]:
# Create summary table
member_summary = (
    df["member_casual"]
      .value_counts()
      .reset_index()
)

member_summary.columns = ["User Type", "Ride Count"]

member_summary

  User Type  Ride Count
0    member     3748418
1    casual     2100256

In [ ]:
# ==========================================
# EDA - Analysis 2
# Bike Type Usage by User Type
# ==========================================

# Count bike types by user category
bike_type = pd.crosstab(df["member_casual"], df["rideable_type"])

bike_type

rideable_type  classic_bike  electric_bike
member_casual
casual               662010        1438246
member              1284169        2464249

In [ ]:
# Percentage within each user type
bike_type_percent = pd.crosstab(
    df["member_casual"],
    df["rideable_type"],
    normalize="index"
) * 100

bike_type_percent.round(2)

rideable_type  classic_bike  electric_bike
member_casual
casual                31.52          68.48
member                34.26          65.74

In [ ]:
# Average ride duration by user type
df.groupby("member_casual")["ride_duration"].mean()

member_casual
casual    22.26114
member    12.47152
Name: ride_duration, dtype: float64

In [ ]:
# Median ride duration
df.groupby("member_casual")["ride_duration"].median()

member_casual
casual    11.270658
member     8.590400
Name: ride_duration, dtype: float64

In [ ]:
# Summary statistics
df.groupby("member_casual")["ride_duration"].describe()

,count,mean,std,min,25%,50%,75%,max
member_casual,,,,,,,,
casual,2100256.0,22.26114,80.434603,0.000767,6.229929,11.270658,20.871250,1574.900183
member,3748418.0,12.47152,32.835596,0.001233,5.026267,8.590400,14.585896,1559.903683

In [ ]:
# Count total rides for each weekday by member type

day_count = pd.crosstab(
    df["day_of_week"],
    df["member_casual"]
)

day_count

member_casual  casual  member
day_of_week
Friday         323398  548706
Monday         245260  527257
Saturday       432826  469572
Sunday         360297  414375
Thursday       267112  601520
Tuesday        234845  592543
Wednesday      236518  594445

In [ ]:
# Create a logical weekday order

order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

In [ ]:
# Rearrange rows using the correct weekday order

day_count = day_count.reindex(order)

day_count

member_casual  casual  member
day_of_week
Monday         245260  527257
Tuesday        234845  592543
Wednesday      236518  594445
Thursday       267112  601520
Friday         323398  548706
Saturday       432826  469572
Sunday         360297  414375

In [ ]:
# Calculate percentage of rides for each weekday

day_percent = pd.crosstab(
    df["day_of_week"],
    df["member_casual"],
    normalize="columns"
) * 100

day_percent = day_percent.reindex(order)

day_percent.round(2)

member_casual  casual  member
day_of_week
Monday          11.68   14.07
Tuesday         11.18   15.81
Wednesday       11.26   15.86
Thursday        12.72   16.05
Friday          15.40   14.64
Saturday        20.61   12.53
Sunday          17.15   11.05

In [ ]:
normalize="columns"

In [ ]:
# Calculate average ride duration by weekday and member type

day_duration = (
    df.groupby(["day_of_week", "member_casual"])["ride_duration"]
      .mean()
      .round(2)
)

day_duration = day_duration.reindex(order, level=0)

day_duration

day_of_week  member_casual
Monday       casual           22.28
             member           12.21
Tuesday      casual           19.35
             member           12.00
Wednesday    casual           18.64
             member           11.97
Thursday     casual           19.58
             member           11.99
Friday       casual           21.90
             member           12.36
Saturday     casual           24.92
             member           13.69
Sunday       casual           25.65
             member           13.67
Name: ride_duration, dtype: float64

In [ ]:
# Count total rides by month for each user type

monthly_count = df.pivot_table(
    index="month_name",
    columns="member_casual",
    values="ride_id",
    aggfunc="count"
)

# Arrange months in calendar order

month_order = [
    "June","July","August","September",
    "October","November","December",
    "January","February","March","April","May"
]

monthly_count = monthly_count.reindex(month_order)

monthly_count

member_casual  casual  member
month_name
June           292006  386795
July           323352  440106
August         337878  452439
September      265268  449294
October        224038  422058
November        99082  257401
December        28090  112455
January         24740  113042
February        41173  160281
March           87850  229165
April          131526  316761
May            245253  408621

In [ ]:
# Calculate percentage distribution within each user type

monthly_percent = (
    monthly_count /
    monthly_count.sum()
    * 100
).round(2)

monthly_percent

member_casual  casual  member
month_name
June            13.90   10.32
July            15.40   11.74
August          16.09   12.07
September       12.63   11.99
October         10.67   11.26
November         4.72    6.87
December         1.34    3.00
January          1.18    3.02
February         1.96    4.28
March            4.18    6.11
April            6.26    8.45
May             11.68   10.90

In [ ]:
# Calculate average ride duration for each month

monthly_duration = df.groupby(
    ["month_name", "member_casual"]
)["ride_duration"].mean().round(2)

monthly_duration

month_name  member_casual
April       casual           19.50
            member           11.57
August      casual           23.61
            member           13.09
December    casual           16.97
            member           11.92
February    casual           16.89
            member           10.84
January     casual           17.67
            member           12.74
July        casual           24.39
            member           13.35
June        casual           25.38
            member           12.94
March       casual           20.09
            member           11.36
May         casual           22.19
            member           12.52
November    casual           17.99
            member           12.08
October     casual           20.47
            member           12.39
September   casual           21.59
            member           12.70
Name: ride_duration, dtype: float64

In [ ]:
# Set correct calendar order

monthly_duration = monthly_duration.reindex(
    month_order,
    level=0
)

monthly_duration

month_name  member_casual
June        casual           25.38
            member           12.94
July        casual           24.39
            member           13.35
August      casual           23.61
            member           13.09
September   casual           21.59
            member           12.70
October     casual           20.47
            member           12.39
November    casual           17.99
            member           12.08
December    casual           16.97
            member           11.92
January     casual           17.67
            member           12.74
February    casual           16.89
            member           10.84
March       casual           20.09
            member           11.36
April       casual           19.50
            member           11.57
May         casual           22.19
            member           12.52
Name: ride_duration, dtype: float64

In [ ]:
# Count total rides for each hour by user type

hourly_count = df.pivot_table(
    index="hour",
    columns="member_casual",
    values="ride_id",
    aggfunc="count"
)

# Display the table

hourly_count

member_casual  casual  member
hour
0               41533   33975
1               26805   20912
2               17803   12624
3                9896    8229
4                7812    9196
5               12308   36092
6               27767  105767
7               51443  210231
8               74061  273154
9               73137  174094
10              88268  148957
11             112574  174324
12             133594  198504
13             138233  194916
14             145775  198527
15             161794  250203
16             185686  355388
17             201063  404939
18             172095  313326
19             129476  217347
20              93979  151822
21              79766  117914
22              67451   85154
23              47937   52823

In [ ]:
# Calculate hourly percentage distribution within each user group

hourly_percent = (
    hourly_count /
    hourly_count.sum()
    * 100
).round(2)

# Display percentage table

hourly_percent

member_casual  casual  member
hour
0                1.98    0.91
1                1.28    0.56
2                0.85    0.34
3                0.47    0.22
4                0.37    0.25
5                0.59    0.96
6                1.32    2.82
7                2.45    5.61
8                3.53    7.29
9                3.48    4.64
10               4.20    3.97
11               5.36    4.65
12               6.36    5.30
13               6.58    5.20
14               6.94    5.30
15               7.70    6.67
16               8.84    9.48
17               9.57   10.80
18               8.19    8.36
19               6.16    5.80
20               4.47    4.05
21               3.80    3.15
22               3.21    2.27
23               2.28    1.41

In [ ]:
# Calculate average ride duration by hour

hourly_duration = (
    df.groupby(["hour", "member_casual"])["ride_duration"]
      .mean()
      .round(2)
)

# Display average duration

hourly_duration

hour  member_casual
0     casual           20.87
      member           12.09
1     casual           22.63
      member           11.90
2     casual           23.18
      member           12.37
3     casual           28.17
      member           13.81
4     casual           19.61
      member           11.57
5     casual           18.10
      member           10.90
6     casual           15.44
      member           11.18
7     casual           15.47
      member           11.37
8     casual           17.08
      member           11.41
9     casual           22.55
      member           11.35
10    casual           25.76
      member           12.21
11    casual           26.17
      member           12.60
12    casual           24.88
      member           12.24
13    casual           25.13
      member           12.46
14    casual           25.29
      member           13.01
15    casual           23.21
      member           12.91
16    casual           21.86
      member           13.17
17    casual           21.37
      member           13.23
18    casual           21.29
      member           13.03
19    casual           20.69
      member           12.74
20    casual           20.28
      member           12.45
21    casual           19.95
      member           12.27
22    casual           20.73
      member           12.53
23    casual           21.31
      member           12.69
Name: ride_duration, dtype: float64

In [ ]:
# Create a readable time label from started_at
df["hour_label"] = (
    df["started_at"].dt.strftime("%I %p")
    + " - " +
    (df["started_at"] + pd.Timedelta(hours=1)).dt.strftime("%I %p")
)

In [ ]:
hourly_count = df.pivot_table(
    index="hour_label",
    columns="member_casual",
    values="ride_id",
    aggfunc="count"
)

In [ ]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,source_file,ride_duration,month,day_of_week,hour,month_name,day,year,hour_label
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,...,member,202506-divvy-tripdata.csv,13.805700,6,Thursday,21,June,5,2025,09 PM - 10 PM
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,...,member,202506-divvy-tripdata.csv,9.755217,6,Saturday,13,June,14,2025,01 PM - 02 PM
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,...,member,202506-divvy-tripdata.csv,9.518333,6,Monday,13,June,9,2025,01 PM - 02 PM
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,...,member,202506-divvy-tripdata.csv,12.091283,6,Sunday,12,June,15,2025,12 PM - 01 PM
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,...,member,202506-divvy-tripdata.csv,10.174667,6,Thursday,7,June,19,2025,07 AM - 08 AM

In [ ]:
# Find the top 10 most frequently used start stations

top_start_overall = (
    df["start_station_name"]
    .value_counts()
    .head(10)
)

top_start_overall

start_station_name
Navy Pier                             50647
DuSable Lake Shore Dr & Monroe St     41630
Michigan Ave & Oak St                 36704
DuSable Lake Shore Dr & North Blvd    35449
Canal St & Madison St                 29409
Theater on the Lake                   28582
Wells St & Concord Ln                 28506
State St & Chicago Ave                28018
Clark St & Elm St                     27897
Millennium Park                       27829
Name: count, dtype: int64

In [ ]:
# Top 10 start stations used by annual members

member_start = (
    df[df["member_casual"] == "member"]["start_station_name"]
    .value_counts()
    .head(10)
)

member_start
# Top 10 start stations used by casual riders

casual_start = (
    df[df["member_casual"] == "casual"]["start_station_name"]
    .value_counts()
    .head(10)
)

casual_start
# Compare the top start stations of members and casual riders

top_start_compare = pd.concat(
    [member_start, casual_start],
    axis=1,
    keys=["Member", "Casual"]
)

top_start_compare

                                     Member   Casual
start_station_name
Canal St & Madison St               22518.0      NaN
Clinton St & Washington Blvd        20867.0      NaN
State St & Chicago Ave              20624.0      NaN
Clinton St & Madison St             20441.0      NaN
Kingsbury St & Kinzie St            20367.0      NaN
Wells St & Elm St                   19456.0      NaN
Wells St & Concord Ln               19205.0      NaN
Clark St & Elm St                   18939.0      NaN
Clinton St & Jackson Blvd           18818.0      NaN
Wells St & Huron St                 18395.0      NaN
Navy Pier                               NaN  38895.0
DuSable Lake Shore Dr & Monroe St       NaN  32879.0
Michigan Ave & Oak St                   NaN  23243.0
DuSable Lake Shore Dr & North Blvd      NaN  20293.0
Millennium Park                         NaN  19127.0
Shedd Aquarium                          NaN  17179.0
Theater on the Lake                     NaN  16511.0
Dusable Harbor                          NaN  15579.0
Streeter Dr & Grand Ave                 NaN  15230.0
Michigan Ave & 8th St                   NaN  11237.0

In [ ]:
# Reset index so station names become a normal column
member_df = member_start.reset_index()
member_df.columns = ["Member Start Station", "Member Rides"]

casual_df = casual_start.reset_index()
casual_df.columns = ["Casual Start Station", "Casual Rides"]

# Merge side by side
top_start_report = pd.concat([member_df, casual_df], axis=1)

top_start_report.index = range(1, len(top_start_report) + 1)
top_start_report.index.name = "Rank"

top_start_report

,Member Start Station,Member Rides,Casual Start Station,Casual Rides
Rank,,,,
1,Canal St & Madison St,22518,Navy Pier,38895
2,Clinton St & Washington Blvd,20867,DuSable Lake Shore Dr & Monroe St,32879
3,State St & Chicago Ave,20624,Michigan Ave & Oak St,23243
4,Clinton St & Madison St,20441,DuSable Lake Shore Dr & North Blvd,20293
5,Kingsbury St & Kinzie St,20367,Millennium Park,19127
6,Wells St & Elm St,19456,Shedd Aquarium,17179
7,Wells St & Concord Ln,19205,Theater on the Lake,16511
8,Clark St & Elm St,18939,Dusable Harbor,15579
9,Clinton St & Jackson Blvd,18818,Streeter Dr & Grand Ave,15230
10,Wells St & Huron St,18395,Michigan Ave & 8th St,11237

In [ ]:
# Find the top 10 end stations used by annual members

member_end = (
    df[df["member_casual"] == "member"]["end_station_name"]
    .value_counts()
    .head(10)
)

member_end

end_station_name
Canal St & Madison St           21962
State St & Chicago Ave          21023
Clinton St & Madison St         20792
Kingsbury St & Kinzie St        20482
Clinton St & Washington Blvd    20194
Clark St & Elm St               19587
Wells St & Concord Ln           19269
Wells St & Elm St               19077
Clinton St & Jackson Blvd       18333
Wells St & Huron St             17596
Name: count, dtype: int64

In [ ]:
# Find the top 10 end stations used by casual riders

casual_end = (
    df[df["member_casual"] == "casual"]["end_station_name"]
    .value_counts()
    .head(10)
)

casual_end

end_station_name
Navy Pier                             39821
DuSable Lake Shore Dr & Monroe St     30140
Michigan Ave & Oak St                 23411
DuSable Lake Shore Dr & North Blvd    22470
Millennium Park                       19945
Theater on the Lake                   17818
Streeter Dr & Grand Ave               15588
Shedd Aquarium                        15051
Dusable Harbor                        13468
Montrose Harbor                       10755
Name: count, dtype: int64

In [ ]:
# Convert Series into DataFrames
member_end_df = member_end.reset_index()
member_end_df.columns = ["Member End Station", "Member Rides"]

casual_end_df = casual_end.reset_index()
casual_end_df.columns = ["Casual End Station", "Casual Rides"]

# Merge side by side for reporting
top_end_report = pd.concat(
    [member_end_df, casual_end_df],
    axis=1
)

# Add ranking
top_end_report.index = range(1, len(top_end_report) + 1)
top_end_report.index.name = "Rank"

top_end_report

,Member End Station,Member Rides,Casual End Station,Casual Rides
Rank,,,,
1,Canal St & Madison St,21962,Navy Pier,39821
2,State St & Chicago Ave,21023,DuSable Lake Shore Dr & Monroe St,30140
3,Clinton St & Madison St,20792,Michigan Ave & Oak St,23411
4,Kingsbury St & Kinzie St,20482,DuSable Lake Shore Dr & North Blvd,22470
5,Clinton St & Washington Blvd,20194,Millennium Park,19945
6,Clark St & Elm St,19587,Theater on the Lake,17818
7,Wells St & Concord Ln,19269,Streeter Dr & Grand Ave,15588
8,Wells St & Elm St,19077,Shedd Aquarium,15051
9,Clinton St & Jackson Blvd,18333,Dusable Harbor,13468
10,Wells St & Huron St,17596,Montrose Harbor,10755

In [ ]:
# Save the cleaned dataset for Tableau visualization

df.to_csv("cyclistic_cleaned.csv", index=False)

In [ ]:
import pandas as pd

# Read the CSV in chunks to avoid MemoryError

total_rows = 0
total_columns = None

for chunk in pd.read_csv("cyclistic_cleaned.csv", chunksize=100000):
    total_rows += len(chunk)

    if total_columns is None:
        total_columns = len(chunk.columns)

print(f"Shape: ({total_rows}, {total_columns})")

Shape: (5848674, 22)

In [ ]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,source_file
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,41.898969,-87.629912,member,202506-divvy-tripdata.csv
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,202506-divvy-tripdata.csv
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,41.889177,-87.638506,member,202506-divvy-tripdata.csv
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,41.920000,-87.650000,member,202506-divvy-tripdata.csv
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,41.940000,-87.690000,member,202506-divvy-tripdata.csv

In [ ]:
# Read only the first 5 rows of the dataset

df = pd.read_csv("cyclistic_cleaned.csv", nrows=5)

df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,source_file,ride_duration,month,day_of_week,hour,month_name,day,year,hour_label
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,...,member,202506-divvy-tripdata.csv,13.805700,6,Thursday,21,June,5,2025,09 PM - 10 PM
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,...,member,202506-divvy-tripdata.csv,9.755217,6,Saturday,13,June,14,2025,01 PM - 02 PM
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,...,member,202506-divvy-tripdata.csv,9.518333,6,Monday,13,June,9,2025,01 PM - 02 PM
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,...,member,202506-divvy-tripdata.csv,12.091283,6,Sunday,12,June,15,2025,12 PM - 01 PM
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,...,member,202506-divvy-tripdata.csv,10.174667,6,Thursday,7,June,19,2025,07 AM - 08 AM

In [ ]:
df.shape

(5848703, 14)

In [ ]:
df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'source_file'],
      dtype='object')

In [ ]:
print(df.columns.tolist())

['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual', 'source_file']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5848703 entries, 0 to 5848702
Data columns (total 14 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             object
 1   rideable_type       object
 2   started_at          object
 3   ended_at            object
 4   start_station_name  object
 5   start_station_id    object
 6   end_station_name    object
 7   end_station_id      object
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       object
 13  source_file         object
dtypes: float64(4), object(10)
memory usage: 624.7+ MB

In [ ]:
# Read only the first 5 rows (very little RAM needed)
import pandas as pd

check_df = pd.read_csv("cyclistic_cleaned.csv", nrows=5)
print(check_df.columns.tolist())

['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual', 'source_file', 'ride_duration', 'month', 'day_of_week', 'hour', 'month_name', 'day', 'year', 'hour_label']

In [ ]:
check_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,source_file,ride_duration,month,day_of_week,hour,month_name,day,year,hour_label
0,0E43949BF937C7DA,electric_bike,2025-06-05 21:24:56.104,2025-06-05 21:38:44.446,Clark St & Armitage Ave,CHI00474,Dearborn Pkwy & Delaware Pl,CHI00306,41.918306,-87.636282,...,member,202506-divvy-tripdata.csv,13.805700,6,Thursday,21,June,5,2025,09 PM - 10 PM
1,1CDEA40FEAF21789,classic_bike,2025-06-14 13:03:34.478,2025-06-14 13:13:19.791,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,...,member,202506-divvy-tripdata.csv,9.755217,6,Saturday,13,June,14,2025,01 PM - 02 PM
2,7ECEB1638575575C,classic_bike,2025-06-09 13:30:22.540,2025-06-09 13:39:53.640,Dearborn Pkwy & Delaware Pl,CHI00306,Kingsbury St & Kinzie St,CHI00299,41.898969,-87.629912,...,member,202506-divvy-tripdata.csv,9.518333,6,Monday,13,June,9,2025,01 PM - 02 PM
3,F275084E25F5A131,electric_bike,2025-06-15 12:48:13.321,2025-06-15 13:00:18.798,Clark St & Elm St,CHI00281,NaN,NaN,41.902970,-87.631300,...,member,202506-divvy-tripdata.csv,12.091283,6,Sunday,12,June,15,2025,12 PM - 01 PM
4,F42E81C85AC722FB,electric_bike,2025-06-19 07:54:26.103,2025-06-19 08:04:36.583,Damen Ave & Cortland St,CHI00388,NaN,NaN,41.915983,-87.677335,...,member,202506-divvy-tripdata.csv,10.174667,6,Thursday,7,June,19,2025,07 AM - 08 AM

In [ ]:
check_df.shape

(5, 22)

In [ ]:
import pandas as pd

check_df = pd.read_csv("cyclistic_cleaned.csv", nrows=5)

print(check_df.shape)
print(check_df.columns.tolist())

(5, 22)
['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual', 'source_file', 'ride_duration', 'month', 'day_of_week', 'hour', 'month_name', 'day', 'year', 'hour_label']

In [ ]:
import pandas as pd

# Read the CSV in chunks to avoid MemoryError
total_rows = 0
total_columns = None

for chunk in pd.read_csv("cyclistic_cleaned.csv", chunksize=100000):
    total_rows += len(chunk)

    if total_columns is None:
        total_columns = len(chunk.columns)

print(f"Total Rows    : {total_rows:,}")
print(f"Total Columns : {total_columns}")
print(f"Shape         : ({total_rows}, {total_columns})")

Total Rows    : 5,848,674
Total Columns : 22
Shape         : (5848674, 22)

In [ ]:
import pandas as pd

# Read the saved CSV file
df_check = pd.read_csv("cyclistic_cleaned.csv")

# Show shape
print(df_check.shape)

(1048575, 22)

In [29]:
print(df.shape)

(5848703, 14)

In [30]:
print(df["source_file"].value_counts())

source_file
202508-divvy-tripdata.csv    790177
202507-divvy-tripdata.csv    763432
202509-divvy-tripdata.csv    714759
202506-divvy-tripdata.csv    678904
202605-divvy-tripdata.csv    653704
202510-divvy-tripdata.csv    646039
202604-divvy-tripdata.csv    448252
202511-divvy-tripdata.csv    356628
202603-divvy-tripdata.csv    317037
202602-divvy-tripdata.csv    201450
202512-divvy-tripdata.csv    140534
202601-divvy-tripdata.csv    137787
Name: count, dtype: int64

In [31]:
print(df.shape)

(5848703, 14)

In [32]:
df.to_csv("cyclistic_cleaned.csv", index=False)

In [33]:
import pandas as pd

df_check = pd.read_csv("cyclistic_cleaned.csv")

print(df_check.shape)

(5848703, 14)

In [34]:
print(df.columns)

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'source_file'],
      dtype='object')

In [35]:
# ----------------------------------------
# Convert date columns into datetime format
# ----------------------------------------

# started_at কে datetime format-এ convert করা
df["started_at"] = pd.to_datetime(df["started_at"])

# ended_at কে datetime format-এ convert করা
df["ended_at"] = pd.to_datetime(df["ended_at"])

# Check data types
df[["started_at", "ended_at"]].dtypes

started_at    datetime64[ns]
ended_at      datetime64[ns]
dtype: object

In [36]:
# ----------------------------------------
# Create ride duration (in minutes)
# ----------------------------------------

# Ride duration = End Time - Start Time
df["ride_duration"] = (
    df["ended_at"] - df["started_at"]
).dt.total_seconds() / 60

# Check first 5 values
df["ride_duration"].head()

0    13.805700
1     9.755217
2     9.518333
3    12.091283
4    10.174667
Name: ride_duration, dtype: float64

In [37]:
# ----------------------------------------
# Create month number
# ----------------------------------------

df["month"] = df["started_at"].dt.month

df["month"].head()

0    6
1    6
2    6
3    6
4    6
Name: month, dtype: int32

In [38]:
# ----------------------------------------
# Create weekday name
# ----------------------------------------

df["day_of_week"] = df["started_at"].dt.day_name()

df["day_of_week"].head()

0    Thursday
1    Saturday
2      Monday
3      Sunday
4    Thursday
Name: day_of_week, dtype: object

In [39]:
# ----------------------------------------
# Create hour column
# ----------------------------------------

df["hour"] = df["started_at"].dt.hour

df["hour"].head()

0    21
1    13
2    13
3    12
4     7
Name: hour, dtype: int32

In [40]:
# ----------------------------------------
# Create month name
# ----------------------------------------

df["month_name"] = df["started_at"].dt.month_name()

df["month_name"].head()

0    June
1    June
2    June
3    June
4    June
Name: month_name, dtype: object

In [41]:
# ----------------------------------------
# Create day of month
# ----------------------------------------

df["day"] = df["started_at"].dt.day

df["day"].head()

0     5
1    14
2     9
3    15
4    19
Name: day, dtype: int32

In [42]:
# ----------------------------------------
# Create year column
# ----------------------------------------

df["year"] = df["started_at"].dt.year

df["year"].head()

0    2025
1    2025
2    2025
3    2025
4    2025
Name: year, dtype: int32

In [ ]:
# ----------------------------------------
# Create readable hour labels
# ----------------------------------------

df["hour_label"] = (
    df["started_at"].dt.strftime("%I %p")
    + " - "
    + (df["started_at"] + pd.Timedelta(hours=1)).dt.strftime("%I %p")
)

In [44]:
# ----------------------------------------
# Check final dataset
# ----------------------------------------

print(df.shape)

print(df.columns)

(5848703, 22)
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'source_file', 'ride_duration', 'month', 'day_of_week',
       'hour', 'month_name', 'day', 'year', 'hour_label'],
      dtype='object')

In [45]:
# Remove invalid ride durations
df = df[df["ride_duration"] > 0]

# Check shape
print(df.shape)

(5848674, 22)

In [46]:
df.to_csv("cyclistic_cleaned.csv", index=False)

In [47]:
print(df.shape)

(5848674, 22)

In [48]:
import pandas as pd

rows = 0

for chunk in pd.read_csv("cyclistic_cleaned.csv", chunksize=100000):
    rows += len(chunk)

print("Total Rows:", rows)

Total Rows: 5848674

In [49]:
import os

print(os.getcwd())

c:\Users\UC\Desktop\Cyclistic_Capstone\NoteBook

In [50]:
df.shape

(5848674, 22)

In [51]:
# Display column names as a list
list(df.columns)

['ride_id',
 'rideable_type',
 'started_at',
 'ended_at',
 'start_station_name',
 'start_station_id',
 'end_station_name',
 'end_station_id',
 'start_lat',
 'start_lng',
 'end_lat',
 'end_lng',
 'member_casual',
 'source_file',
 'ride_duration',
 'month',
 'day_of_week',
 'hour',
 'month_name',
 'day',
 'year',
 'hour_label']